In [1]:
#### ML 머신러닝에 대해 알아보자 ################################

In [ ]:
#데이터 분석 직무  - domain 지식 지식으로 Machine Learning 용 데이터 셋 구성하고 ML로 결론 유도
#데이터 사이언티스트 - ML 알고리즘 튜닝으로 ML 분석 효율 향상
#데이터 엔지니어 - 일반 it엔지니어

In [2]:
# 머신 러닝은 기계가 학습하여 결과를 예측하여 결과값을 내게 하는 것이다.

In [3]:
# 머신 러닝 = 기관총 --> 끊임 없이 데이터 / 총알이 보급이 되어야 한다. --> 기계가 학습할 수 있도록 꾸준히 데이터 제공

In [31]:
#설치
#!pip install scikit-learn

#기본
import pandas as pd
import numpy as np


# seaborn의 데이터를 시각화하는 모듈을 가져오는 것이다.
import seaborn as sns
# 라벨 인코더에 대해 알아보자
from sklearn.preprocessing import LabelEncoder

# 데이터 값을 피팅하는 DecisionTreeClassfier
from sklearn.tree import DecisionTreeClassifier

In [17]:
# 타이타닉호에 들어가기 전에 하나의 기술에 대해 알아보자
# LabelEncoder 활용

d={"name":["사과","바나나","체리","두리안","바나나"],
   "color":["red","yellow", "red", "yellow","yellow"]}
fruit_df = pd.DataFrame(d)
fruit_df

name   color
0   사과     red
1  바나나  yellow
2   체리     red
3  두리안  yellow
4  바나나  yellow

In [18]:
fruit_df["name"]

0     사과
1    바나나
2     체리
3    두리안
4    바나나
Name: name, dtype: object

In [19]:
# 라벨 인코더란 : 일반형 범부 ("사과","바나나" 이런 것들)
#                   --> 숫자형으로 표현하기 위해서
# 즉 일반형을 숫자로 라벨을 붙인다.

LE=LabelEncoder()
LE.fit_transform(fruit_df["name"])

# 아래의 array를 보면
# 두리안 --> 0
# 바나나 --> 1
# 사과   --> 2
# 체리   --> 3
# 이렇게 숫자 라벨을 붙여버린다.

# 이런방법을 통하여 object 형식 female male을 숫자나 true(1) false(0) 으로 표현할 수 있따.
# 라벨 인코더는 0 ~ 5 는 숫자에 가중치가 존재하니 아래의 get_dummies로 표현

array([2, 1, 3, 0, 1])

In [20]:
# 방법 2 : pandas의 dummies 로 위의 표
names_df = pd.get_dummies(fruit_df["name"])
names_df

두리안    바나나     사과     체리
0  False  False   True  False
1  False   True  False  False
2  False  False  False   True
3   True  False  False  False
4  False   True  False  False

In [21]:
fruit_df_ohe = pd.concat([names_df, fruit_df["color"]], axis = 1)
fruit_df_ohe

두리안    바나나     사과     체리   color
0  False  False   True  False     red
1  False   True  False  False  yellow
2  False  False  False   True     red
3   True  False  False  False  yellow
4  False   True  False  False  yellow

In [22]:
# 방법 3: onehotEncoder

from sklearn.preprocessing import OneHotEncoder
name_np = fruit_df["name"].to_numpy()
name_np

array(['사과', '바나나', '체리', '두리안', '바나나'], dtype=object)

In [23]:
#형태를 reshape 해줄 떄
name_np = name_np.reshape(-1,1)
name_np

array([['사과'],
       ['바나나'],
       ['체리'],
       ['두리안'],
       ['바나나']], dtype=object)

In [24]:
#위의 형태를 결과 값(0,1)으로 표현!!!
OneHotEncoder().fit_transform(name_np).toarray()

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
############  본   론 #################################################################################

In [ ]:
#######################################################################################################

In [6]:
# 타이타닉호에 대해 알아보자

In [8]:
# 데이터셋 로드
df = sns. load_dataset("titanic")
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [9]:
# 컬럼의정보 보기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [10]:
# 각 컬럼의 정보들 참조
df["pclass"].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [11]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [12]:
# 필요한 도메인만 가져오기
df3= df[["survived", "pclass", "sex", "age", "sibsp", "parch", "fare"]]
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [13]:
# age에서  NaN값이 존재한다  -- > NaN 자료들 자르기 
df3 = df3.dropna()
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  714 non-null    int64  
 1   pclass    714 non-null    int64  
 2   sex       714 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     714 non-null    int64  
 5   parch     714 non-null    int64  
 6   fare      714 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 44.6+ KB


In [25]:
# 성별은 object 형태로 존재 --> 위의 라벨 인코더 방법 2
# pd.getdummies 형태로 2의 female, male --> 0,1 (True or False) 형태로 Encoder

sex_df= pd.get_dummies(df3["sex"])
sex_df

female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
885    True  False
886   False   True
887    True  False
889   False   True
890   False   True

[714 rows x 2 columns]

In [28]:
# 력롸 값 타이타닉
titanic = pd.concat([df3, sex_df], axis = 1)
del titanic["sex"] # sex의 female male 컬럼을 지우고 --> female/ male 컬럼으로 true fasle 값이 나오게
titanic[:2]

survived  pclass   age  sibsp  parch     fare  female   male
0         0       3  22.0      1      0   7.2500   False   True
1         1       1  38.0      1      0  71.2833    True  False

In [29]:
# 커브를 피팅하기 위해서 함수 값 설정
# y = f(x)
y = titanic["survived"]
del titanic["survived"]
x = titanic

In [32]:
dt = DecisionTreeClassifier()
dt.fit(x,y)

DecisionTreeClassifier()

In [34]:
#  다음의 값이 결과 값을 확인해보자
dt.predict([[3, 22.0, 1, 0, 7.2500, False, True]])

C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [ ]:
# 아래의 결과 테이블을 보도록 하자.

In [35]:
y # 생존을 한 결과 : 생존했는지 안했는지. (총 NaN을 제외한 714명의 결과)

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: survived, Length: 714, dtype: int64

In [36]:
x # 생존을 한 원인 (머신러닝을 위해 결과값이 나오는 원인들을 확인)

pclass   age  sibsp  parch     fare  female   male
0         3  22.0      1      0   7.2500   False   True
1         1  38.0      1      0  71.2833    True  False
2         3  26.0      0      0   7.9250    True  False
3         1  35.0      1      0  53.1000    True  False
4         3  35.0      0      0   8.0500   False   True
..      ...   ...    ...    ...      ...     ...    ...
885       3  39.0      0      5  29.1250    True  False
886       2  27.0      0      0  13.0000   False   True
887       1  19.0      0      0  30.0000    True  False
889       1  26.0      0      0  30.0000   False   True
890       3  32.0      0      0   7.7500   False   True

[714 rows x 7 columns]

In [ ]:
## 이런 결과 값들을 통해 어디구간에서 남자 여자 가족  나의 등의 여러 변수요인들을 고려했을 때
## 생존을 하기 위해서는 어떤 특성이 있는지
## 어떤 조건이 구해졌을 때 생존을 할지 안할지를 예측할 수 있다.

In [37]:
## ex) 배클래스(quality) : 1등급   / 나이 : 40  /  가족 : 1   / parch 0  /  fare 30.0000  /  남자 였을 때  이사람을 살았을까?

dt.predict([[1, 40.0, 1, 0, 30.0000, False, True]])

C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [ ]:
## 결과 --> 뒤졌따.